package org.motechproject.sms.audit;

//todo: motechTimestanp & providerTimestamp instead of just timestamp?
//todo: 'senderNumber' & 'recipientNumber' instead of 'phoneNumber'?

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.joda.time.DateTime;
import org.motechproject.commons.date.util.DateUtil;
import org.motechproject.mds.annotations.Access;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.util.SecurityMode;

import static org.motechproject.sms.util.Constants.VIEW_SMS_LOGS_PERMISSION;

/**
 * SMS audit record for the database.
 */
@Entity(nonEditable = true)
@Access(value = SecurityMode.PERMISSIONS, members = {VIEW_SMS_LOGS_PERMISSION})
public class SmsRecord {

    /**
     * The name of the configuration to which this SMS should be associated with.
     */
    private String config;

    /**
     * The direction of the SMS - either inbound or outbound.
     */
    private SmsDirection smsDirection;

    /**
     * The phone number to which this SMS was sent, or which it was received.
     */
    private String phoneNumber;

    /**
     * The content of the SMS message.
     */
    private String messageContent;

    /**
     * The timestamp for this SMS.
     */
    private DateTime timestamp;

    /**
     * The delivery status for this SMS.
     */
    private DeliveryStatus deliveryStatus;

    private String providerStatus;

    /**
     * The ID by which MOTECH identifies this SMS.
     */
    private String motechId;

    /**
     * The ID generated by the provider for this SMS.
     */
    private String providerId;

    /**
     * The error message for this SMS, if applicable.
     */
    private String errorMessage;

    /**
     * Constructs a new instance of a record without filling out any fields.
     */
    public SmsRecord() {
        this(null, null, null, null, null, null, null, null, null, null);
    }

    /**
     * Constructs a new instance using the provided data.
     * @param config the name of the configuration to which this SMS should be associated with
     * @param smsDirection the direction of the SMS - either inbound or outbound
     * @param number the phone number to which this SMS was sent, or which it was received
     * @param message the content of the SMS message
     * @param timestamp the timestamp for this SMS
     * @param deliveryStatus the delivery status for this SMS
     * @param providerStatus
     * @param motechId the ID by which MOTECH identifies this SMS.
     * @param providerId the ID generated by the provider for this SMS
     * @param errorMessage the error message for this SMS, if applicable
     */
    public SmsRecord(String config, SmsDirection smsDirection, String number,  //NO CHECKSTYLE ParameterNumber
                     String message, DateTime timestamp, DeliveryStatus deliveryStatus, String providerStatus,
                     String motechId, String providerId, String errorMessage) {
        this.config = config;
        this.smsDirection = smsDirection;
        this.phoneNumber = number;
        this.messageContent = message;
        this.timestamp = timestamp;
        this.deliveryStatus = deliveryStatus;
        this.providerStatus = providerStatus;
        this.motechId = motechId;
        this.providerId = providerId;
        this.errorMessage = errorMessage;
    }

    /**
     * @return the name of the configuration to which this SMS should be associated with
     */
    public String getConfig() {
        return config;
    }

    /**
     * @param config the name of the configuration to which this SMS should be associated with
     */
    public void setConfig(String config) {
        this.config = config;
    }

    /**
     * @return the direction of the SMS - either inbound or outbound
     */
    public SmsDirection getSmsDirection() {
        return smsDirection;
    }

    /**
     * @param smsDirection the direction of the SMS - either inbound or outbound
     */
    public void setSmsDirection(SmsDirection smsDirection) {
        this.smsDirection = smsDirection;
    }

    /**
     * @return the phone number to which this SMS was sent, or which it was received
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber the phone number to which this SMS was sent, or which it was received
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return the content of the SMS message
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * @param messageContent he tcontent of the SMS message
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    /**
     * @return the timestamp for this SMS
     */
    public DateTime getTimestamp() {
        return DateUtil.setTimeZoneUTC(timestamp);
    }

    /**
     * @param timestamp the timestamp for this SMS
     */
    public void setTimestamp(DateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * @return the delivery status for this SMS
     */
    public DeliveryStatus getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * @param deliveryStatus the delivery status for this SMS
     */
    public void setDeliveryStatus(DeliveryStatus deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }

    public String getProviderStatus() {
        return providerStatus;
    }

    public void setProviderStatus(String providerStatus) {
        this.providerStatus = providerStatus;
    }

    /**
     * @return the ID by which MOTECH identifies this SMS.
     */
    public String getMotechId() {
        return motechId;
    }

    /**
     * @param motechId the ID by which MOTECH identifies this SMS.
     */
    public void setMotechId(String motechId) {
        this.motechId = motechId;
    }

    /**
     * @return the ID generated by the provider for this SMS
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * @param providerId the ID generated by the provider for this SMS
     */
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    /**
     * @return the error message for this SMS
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * @param errorMessage the error message for this SMS
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    @Override
    public boolean equals(Object obj) {
        return EqualsBuilder.reflectionEquals(this, obj);
    }

    @Override
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this);
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }
}
