package org.motechproject.hub.mds.service;

import org.motechproject.hub.mds.HubDistributionContent;
import org.motechproject.mds.service.MotechDataService;

/**
 * Data Service interface for {@link org.motechproject.hub.mds.HubDistributionContent}.
 * The implementation is generated by the Motech Data Services module at runtime.
 */
public interface HubDistributionContentMDSService extends
        MotechDataService<HubDistributionContent> {

}
