package org.motechproject.hub.mds.service;

import org.motechproject.hub.mds.HubPublisherTransaction;
import org.motechproject.mds.annotations.Lookup;
import org.motechproject.mds.annotations.LookupField;
import org.motechproject.mds.service.MotechDataService;

import java.util.List;

/**
 * Data Service interface for {@link org.motechproject.hub.mds.HubPublisherTransaction}.
 * The implementation is generated by the Motech Data Services module at runtime.
 */
public interface HubPublisherTransactionMDSService extends
        MotechDataService<HubPublisherTransaction> {

    /**
     * Finds all <code>HubPublisherTransaction</code>s with given topic id.
     *
     * @param hubTopicId the id of the topic
     * @return list of the matching publisher transactions
     */
    @Lookup(name = "By hubTopicId")
    List<HubPublisherTransaction> findPubTransactionByTopicId(
            @LookupField(name = "hubTopicId") Integer hubTopicId);

}
