package org.motechproject.hub.mds.service;

import org.motechproject.hub.mds.HubSubscriberTransaction;
import org.motechproject.mds.annotations.Lookup;
import org.motechproject.mds.annotations.LookupField;
import org.motechproject.mds.service.MotechDataService;

import java.util.List;

/**
 * Data Service interface for {@link org.motechproject.hub.mds.HubSubscriberTransaction}.
 * The implementation is generated by the Motech Data Services module at runtime.
 */
public interface HubSubscriberTransactionMDSService extends
        MotechDataService<HubSubscriberTransaction> {

    /**
     * Finds all <code>HubSubscriberTransaction</code>s with given subscription id.
     *
     * @param hubSubscriptionId the id of the subscription
     * @return list of the matching subscriber transactions
     */
    @Lookup(name = "By hubSubscriptionId")
    List<HubSubscriberTransaction> findSubTransBySubId(
            @LookupField(name = "hubSubscriptionId") Integer hubSubscriptionId);

}
