package org.motechproject.hub.mds.service;

import org.motechproject.hub.mds.HubTopic;
import org.motechproject.mds.annotations.Lookup;
import org.motechproject.mds.annotations.LookupField;
import org.motechproject.mds.service.MotechDataService;

import java.util.List;

/**
 * Data Service interface for {@link org.motechproject.hub.mds.HubTopic}.
 * The implementation is generated by the Motech Data Services module at runtime.
 */
public interface HubTopicMDSService extends MotechDataService<HubTopic> {

    /**
     * Finds all <code>HubTopic</code>s with given topic url.
     *
     * @param topicUrl the url of the topic
     * @return list of the matching hub topics
     */
    @Lookup(name = "By Topic URL")
    List<HubTopic> findByTopicUrl(@LookupField(name = "topicUrl") String topicUrl);
}
