package org.motechproject.dhis2.repository;

import org.motechproject.dhis2.domain.DataSet;
import org.motechproject.mds.service.MotechDataService;

/**
 * This service provides data access for {@link DataSet}.
 * The implementation is generated by Motech Data Services and published as an OSGi service.
 */
public interface DataSetDataService extends MotechDataService<DataSet> {

}
