package org.motechproject.appointments.domain;

import org.joda.time.DateTime;
import org.joda.time.Period;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

import javax.jdo.annotations.Unique;
import java.util.UUID;

/**
 * Appointment class to track the appointments of a person identified by externalId
 */
@Entity
public class Appointment {

    // External id of the person for whom this appointment tracks
    @Field (required = true)
    private String externalId;

    // Appointment id generated by the system
    @Field
    @Unique
    private String apptId;

    // Due date for the appointment
    @Field
    private DateTime appointmentDate;

    // Date of the fulfilled visit
    @Field
    private DateTime visitedDate;

    // Status flag to indicate if the appointment was missed
    @Field
    private AppointmentStatus status;

    // Flag to activate or deactivate sending reminders
    @Field
    private boolean sendReminders;

    // Reminder interval in seconds
    @Field
    private Period reminderInterval;

    // Time to start firing the reminder events
    @Field
    private DateTime reminderStartTime;

    public Appointment() { this("", null, null, AppointmentStatus.NONE, false, null, null); }

    public Appointment(String externalId, DateTime appointmentDate, DateTime visitedDate, AppointmentStatus status, boolean sendReminders, Period reminderInterval, DateTime reminderStartTime) {
        this.externalId = externalId;
        this.apptId = UUID.randomUUID().toString();
        this.appointmentDate = appointmentDate;
        this.visitedDate = visitedDate;
        this.status = status;
        this.sendReminders = sendReminders;
        this.reminderInterval = reminderInterval;
        this.reminderStartTime = reminderStartTime;
    }

    // Getters & Setters
    public String getExternalId() { return this.externalId; }

    public void setExternalId(String externalId) { this.externalId = externalId; }

    public String getApptId() { return this.apptId; }

    public DateTime getAppointmentDate() { return this.appointmentDate; }

    public void setAppointmentDate(DateTime appointmentDate) { this.appointmentDate = appointmentDate; }

    public DateTime getVisitedDate() { return this.visitedDate; }

    public void setVisitedDate(DateTime visitedDate) { this.visitedDate = visitedDate; }

    public AppointmentStatus getStatus() { return this.status; }

    public void setStatus(AppointmentStatus status) { this.status = status; }

    public boolean getSendReminders() { return this.sendReminders; }

    public void setSendReminders(boolean sendReminders) { this.sendReminders = sendReminders; }

    public Period getReminderInterval() { return this.reminderInterval; }

    public void setReminderInterval(Period interval) { this.reminderInterval = interval; }

    public DateTime getReminderStartTime() { return this.reminderStartTime; }

    public void setReminderStartTime(DateTime startTime) { this.reminderStartTime = startTime; }
}
