package org.motechproject.openmrs.service;

import org.motechproject.openmrs.domain.GeneratedIdentifier;

/**
 * Interface for handling generated identifiers from the OpenMRS's ID Gen Module.
 */
public interface OpenMRSGeneratedIdentifierService {

    /**
     * Returns identifier generated by Generator with given {@code sourceName}.
     * Configuration with the given {@code configName} will be used while performing this action.
     *
     * @param configName the name of the configuration
     * @param sourceName the Source Name of the ID Generator
     * @return latest generated identifier
     */
    GeneratedIdentifier getLatestIdentifier(String configName, String sourceName);
}
