package org.motechproject.messagecampaign.dao;

import org.motechproject.mds.annotations.Lookup;
import org.motechproject.mds.annotations.LookupField;
import org.motechproject.mds.service.MotechDataService;
import org.motechproject.messagecampaign.domain.campaign.CampaignType;
import org.motechproject.messagecampaign.domain.campaign.CampaignMessageRecord;

import java.util.List;

/**
 * Data Service interface for {@link CampaignMessageRecord}s. The implementation is generated by
 * the Motech Data Services module.
 */
public interface CampaignMessageRecordService extends MotechDataService<CampaignMessageRecord> {

    /**
     * Finds all {@link CampaignMessageRecord}s with the given name.
     *
     * @param name the name of the campaign message record
     * @return campaign message records with the given name
     */
    @Lookup
    List<CampaignMessageRecord> findByName(@LookupField(name = "name") String name);

    /**
     * Finds all {@link CampaignMessageRecord}s with the given name and of the given type.
     *
     * @param messageType the {@link CampaignType} of the campaign message records
     * @param name the name of the campaign message records
     * @return campaign message records of the given name and type
     */
    @Lookup(name = "Find messages by name")
    List<CampaignMessageRecord> findByNameAndType(@LookupField(name = "messageType") CampaignType messageType,
                                                  @LookupField(name = "name") String name);
}
