package org.motechproject.messagecampaign.dao;

import org.motechproject.mds.annotations.Lookup;
import org.motechproject.mds.annotations.LookupField;
import org.motechproject.mds.service.MotechDataService;
import org.motechproject.messagecampaign.domain.campaign.CampaignEnrollment;
import org.motechproject.messagecampaign.domain.campaign.CampaignEnrollmentStatus;

import java.util.List;

/**
 * Data Service interface for {@link CampaignEnrollment}s. The implementation is generated by
 * the Motech Data Services module.
 */
public interface CampaignEnrollmentDataService extends MotechDataService<CampaignEnrollment> {

    /**
     * Finds all {@link CampaignEnrollment}s of the given campaign name.
     *
     * @param campaignName name of the campaign
     * @return all campaign enrollments of the given campaign name
     */
    @Lookup
    List<CampaignEnrollment> findByCampaignName(@LookupField(name = "campaignName") String campaignName);

    /**
     * Finds all {@link CampaignEnrollment}s of the given enrollment status.
     *
     * @param status the {@link CampaignEnrollmentStatus} of the campaign enrollment
     * @return all campaign enrollments of the given enrollment status
     */
    @Lookup
    List<CampaignEnrollment> findByStatus(@LookupField(name = "status") CampaignEnrollmentStatus status);

    /**
     * Finds all {@link CampaignEnrollment}s of the given external ID.
     *
     * @param externalId the external ID of the campaign enrollment
     * @return all campaign enrollments with the given external ID
     */
    @Lookup
    List<CampaignEnrollment> findByExternalId(@LookupField(name = "externalId") String externalId);

    /**
     * Finds the {@link CampaignEnrollment} of the given external ID and campaign name.
     *
     * @param externalId the externalId of the campaign enrollment
     * @param campaignName name of the campaign
     * @return the campaign enrollment of the given external ID and campaign name or null, if not found
     */
    @Lookup
    CampaignEnrollment findByExternalIdAndCampaignName(@LookupField(name = "externalId") String externalId,
                                                       @LookupField(name = "campaignName") String campaignName);

}
