package org.motechproject.http.agent.service;

import org.motechproject.http.agent.domain.HTTPActionRecord;
import org.motechproject.mds.service.MotechDataService;

/**
 * The <code>HTTPActionService</code> interface provides methods for everything connected with logging the actions of the HTTP Agent module
 * The implementation is generated by Motech Data Services
 */
public interface HTTPActionService extends MotechDataService<HTTPActionRecord> {

}
